### PR TITLE
Add discord integration

### PR DESCRIPTION
**Pull request by ABootleg53**
Add discord webhook integration. This should go into /noah/.noah or in bash noah.sh config

### CODE REVIEW

**Comment by faustbrian** [comment]
It's called nowhere, you just added a variable 🤔

**Comment by ABootleg53** [comment]
Hm I am new to this github thing, there is another component lol

**Comment by faustbrian** [comment]
You would need to integrate it here https://github.com/faustbrian/noah/blob/master/modules/notifications.sh.

Add discord to the `notify` method and then implement a `notify_via_discord` method that sends all required data to the discord API.

**Comment by ABootleg53** [comment]
Yes I did that :) i do not think i made a pull request correctly lol

**Pull request merged**
